### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by belohlavek** [shokai/arduino_firmata#18]
When I run a simple script:

require 'rubygems'
require 'arduino_firmata'

arduino = ArduinoFirmata.connect
arduino.digital_write 13, true
sleep

I get:

/var/lib/gems/1.9.1/gems/arduino_firmata-0.2.3/lib/arduino_firmata/arduino.rb:163:in `write_nonblock': Resource temporarily unavailable - write would block (Errno::EAGAIN)

Somehow if I execute the scripts too quickly i get the error, but if I wait then the error vanishes and works, how can I fix this?

**Comment by belohlavek** [comment]
Never mind, kids: never forget to add "arduino.close" at the end of your scripts!

Edit: Still closing it at the end I get the error some times :-(

**Comment by shokai** [comment]
you should write
- OS Name
- ArduinoBoard Name
- Ruby version

**Comment by belohlavek** [comment]
Ubuntu 12.10
Arduino UNO
Ruby 1.9.3 but I tried to downgrade it to the lastest dev version, yet when I do "ruby -v" I get 1.9.3

**Comment by shokai** [comment]
Hi

I've tried Ubuntu+Arduino UNO on VirtualBox, but it not recognize Arduino.

<img src="http://gyazo.com/4167657b88a6af45370b1696e68d0345.png">

I'm looking for no-VM ubuntu laptop.

**Comment by shokai** [comment]
I disabled nonblocking IO and all tests was passed.
