### ISSUE TITLE
Arduino.on(:digital_read) returns pin value of 0 

### ISSUE THREAD

**Issue by emilesilvis** [shokai/arduino_firmata#33]
I use an Arduino UNO version 2.3. When I do:

``` ruby
require 'arduino_firmata'

arduino = ArduinoFirmata.connect

puts "firmata version #{arduino.version}"

arduino.pin_mode 8, ArduinoFirmata::INPUT
puts arduino.digital_read(8)

loop do
  arduino.on(:digital_read) do |pin, status|
    #if pin == 8
      puts "digital pin #{pin} changed : #{status}"
    #end
  end
  sleep(0.1)
end
```

I always get a pin value of 0 (`digital pin 0 changed : true`). Consequently the `if` block doesn't execute correctly either, so I've commented it out here. 

Is this a feature (and I'm just doing something wrong) or a bug?

**Comment by emilesilvis** [comment]
https://github.com/shokai/arduino_firmata/blob/master/samples/on_digital_read.rb seems to do the same.

**Comment by shokai** [comment]
Hi. <a href="https://github.com/shokai/arduino_firmata/blob/master/samples/on_digital_read.rb">the sample code</a> is not same.
You should use `arduino.on :digital_read` at outside of loop.

Because it is a function to register the event for pin change.
If you use it inside of loop, it registers many pin-change-events.

**Comment by emilesilvis** [comment]
Hi, thanks, it makes sense that it should sit outside the loop. However, I think I tried the sample code exactly as it is there and it did the same thing. I will confirm this though. Does that sample code give you the right value for the pin parameter?

**Comment by emilesilvis** [comment]
@shokai , my apologies. I've confirmed, and the sample code does work as expected. I'll close the issue.
